version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: badmos
      POSTGRES_DB: youtube_fetcher
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=badmos
      - DB_NAME=youtube_fetcher
      - SEARCH_QUERY=breaking news|live news|news today|world news|current events|latest updates
      - FETCH_INTERVAL=60
      - PORT=8080
    ports:
      - "8080:8080"
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  postgres_data: